### PR TITLE
Fix broken documentation links in README.md

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by lurch** [comment]
@hedss Okay, what have I done wrong? ;)

**Comment by hedss** [comment]
@lurch I have no idea what the `none` change type is, but it's not `versionist` :)

**Comment by hedss** [comment]
Also, see https://resin-io-modules.github.io/resin-procbots/

This is what the README.md is currently designed for. This patch would break that, rendering the links useless.

**Comment by lurch** [comment]
> I have no idea what the none change type is, but it's not `versionist` :)

Oh? https://github.com/resin-io/versionist/pull/81

> This is what the README.md is currently designed for. This patch would break that, rendering the links useless.

Ah, I didn't realise that, sorry! :(  I was simply looking at the links as displayed on https://github.com/resin-io-modules/resin-procbots
BTW when I go to https://resin-io-modules.github.io/resin-procbots/ and click on either the "Architecture" or "SyncBot" links, they just get displayed as raw markdown, rather than being nicely formatted and without displaying their images??

Closing this PR as invalid.

**Comment by lurch** [comment]
Perhaps the https://resin-io-modules.github.io/resin-procbots/ URL could be displayed in the one-line project description at the top of https://github.com/resin-io-modules/resin-procbots ?

**Comment by hedss** [comment]
> > I have no idea what the none change type is, but it's not versionist :)
> Oh? resin-io/versionist#81

I sit very much corrected! Never saw this, that means VB needs updating too.

**Comment by lurch** [comment]
>>> I have no idea what the none change type is, but it's not versionist :)

>> Oh? resin-io/versionist#81

> I sit very much corrected! Never saw this, that means VB needs updating too.

Ping @craig-mulligan ;-)

> Annoyingly, for me in FF, they get downloaded and then displayed in an editor.

I guess that's probably a mimetype-handling issue.

> I'm not sure there's an easy way to get it to display markdown from a link, though I think I'll have a nose.

I guess if not, perhaps the solution is to manually re-add them to the repo in HTML format instead?

**Comment by hedss** [comment]
> I'm not sure there's an easy way to get it to display markdown from a link, though I think I'll have a nose.

I really want to avoid that if I can't help it. :-/

**Comment by lurch** [comment]
Ahhh, it looks like the `.nojekyll` ( #122 ) is precisely what's stopping the markdown being converted to html automatically :-/  https://stackoverflow.com/questions/15044353/github-pages-how-do-i-edit-this-page-in-markdown-format-just-as-i-created-it

**Comment by hedss** [comment]
It didn't work before adding the `.nojekyll`, so I believe something else is going on.

**Pull request closed without merging**
