### PR TITLE
SyncBot: Store connections as tags in Flowdock

### PR DESCRIPTION
**Pull request by sqweelygig**
* Store connections as tags in Flowdock
* While I was there my IDE advised me about readonly and protected abstract constructors
* While I was there removed a console.log that had sneaked in
* While I was there fixed a couple of changelog entries that hadn't been created correctly

Change-Type: patch
Connects-To: #416

---
##### Contributor checklist

- [x] Build output been rebuilt and tested
- [ ] Introduces security considerations
- [x] Tests are included
- [ ] Documentation is added or changed
- [ ] Affects the development, build or deployment processes of the component

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---
---- Autogenerated Waffleboard Connection: Connects to #416

### CODE REVIEW

**Comment by sqweelygig** [comment]
@hedss this PR has work downstream of it, and fixes one of @alexandrosm 's specifically raised issues around the UX of SyncBot.  It would be an excellent candidate for prioritising above my other PRs.

**Comment by lekkas** [comment]
@sqweelygig can you please add an example somewhere in the description of how these connections as tags will appear in Flowdock? an example of a tag and how people can use it should be more than enough

**Comment by sqweelygig** [comment]
Attached is a screen shot of one of my E2E test threads.  It was created on Discourse and has then been synced to Flowdock and Front.
@lekkas: note the reduction in "mirrored in" comments.  These are now stored in Flowdock's tags as `mirror:blahblahblah` which Flowdock chooses not to render because of the `:`
@hedss further details as requested, would appropriate action for me to take at this stage be to reject your review and request a re-review now the more complete information is present?
front
flowdock
discourse

**Comment by hedss** [comment]
@sqweelygig Cool, makes sense to me. No need to re-review, happy for Approval to stand.

**Pull request merged**
