### PR TITLE
Add files suitable for usage as chat avatar.

### PR DESCRIPTION
**Pull request by sqweelygig**
Connect to #192 

* Add and attribute a cartoon robot svg.
* Render a version of the robot in 1:1 aspect ratio.

Change-Type: patch

### CODE REVIEW

**Comment by sqweelygig** [comment]
I'm going to wait upon @sonyagreen's approval on this; because user support is her circus, I'm just a monkey.

**Comment by sqweelygig** [comment]
Hey, I had 15 minutes waiting for a support shift to end before I could get tea, so I made SyncBot's avatar more Resin coloured.

**Comment by sqweelygig** [comment]
@sonyagreen in case the last message didn't hit your "I should do something" pattern matching; this is an suggestion as to a SyncBot avatar; do you approve?

**Comment by hedss** [comment]
@sqweelygig If you re-add Sonya as a reviewer, it should wind up pinging her properly.

**Pull request merged**
