### PR TITLE
SyncBot: No longer escape HTML when passing to Front's MD endpoints

### PR DESCRIPTION
**Pull request by sqweelygig**
* Remove escaping of HTML when creating a comment

Front seem to have fixed the parsing of comment text.
Tested with the literal strings:
* A message with `>` in it
* A message with > in it
* **bold**
* [link](www.google.co.uk)
* <test
* quoite
  > this
* ```
  code-block
  ```

Change-Type: patch
Connects-to: https://github.com/resin-io-modules/resin-procbots/issues/469

---
##### Contributor checklist
<!-- For completed items, change [ ] to [x].  -->
- [x] Build output been rebuilt and tested
- [ ] Introduces security considerations
- [ ] Tests are included
- [ ] Documentation is added or changed
- [ ] Affects the development, build or deployment processes of the component

##### Reviewer Guidelines
- When submitting a review, please pick:
  - '*Approve*' if this change would be acceptable in the codebase (even if there are minor or cosmetic tweaks that could be improved).
  - '*Request Changes*' if this change would not be acceptable in our codebase (e.g. bugs, changes that will make development harder in future, security/performance issues, etc).
  - '*Comment*' if you don't feel you have enough information to decide either way (e.g. if you have major questions, or you don't understand the context of the change sufficiently to fully review yourself, but want to make a comment)
---

### CODE REVIEW

**Comment by hedss** [comment]
@sqweelygig PR description includes 'Change-type' twice, has no 'Connects-to:' and has fields that should be removed (HQ, See, etc).

**Comment by sqweelygig** [comment]
^^ specifically comments, this change does not affect replies ^^

**Comment by hedss** [comment]
@sqweelygig Is it worth adding code to ensure that this is then tested so consistent output is achieved? Additionally, which Issue is this PR related to, I still can't see a `Connects-to:` in the commit (or the description).

**Comment by sqweelygig** [comment]
Issue added for End to End testing, because it would not form a trivial unit of work.

**Comment by hedss** [comment]
@sqweelygig I think I was confusing. When I originally said to test for it, I meant in the Front translator code to ensure that the right operation was carried out depending on what it received back. :)

As an aside, can we have an issue number for every PR and branch please, to follow the Commit and PR guidelines (ie. this would have been `469-fix-html-quoting-breaking-metadata`.

**Pull request merged**
