### PR TITLE
Ensure that unlabeling of PRs is ignored.

### PR DESCRIPTION
**Pull request by hedss**
This ensures that checks to see if a PR is mergable is not carried out.
Whilst VersionBot won't attempt to create a new merge, it will complain that
it can't. This means that scripted labeling/unlabeling of a PR will have an
error attached at the end of a successful merge. We need to quash this.

Also lower number of retries to a total of 3.

Connects to #37

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
> will have an error attached at the end of a successful merge

Is there any way for VersionBot to check if a PR has already been merged?

**Comment by hedss** [comment]
No, the closest you can get is look for an unattached head. However, this is actually a pointless check, as VersionBot shouldn't even be triggered in this case (which this issues fixes).

**Comment by lurch** [comment]
Related question: Is VersionBot able to detect (and ignore) closed PRs? Or when a PR gets closed without merging, does the user need to remember to add the `procbots/versionbot/no-checks` label?

**Comment by hedss** [comment]
No, it only acts on particular PRs which are being opened, synchronized or labeled. It ignores everything else.

To be clear, VersionBot has a very specific role, the versioning up and merging of PRs. There may well be (and we are discussing) other ProcBot based bots that will have other tasks.

**Comment by lurch** [comment]
The reason I ask, is because if #6 gets implemented, it might get annoying if VersionBot (and/or some other ProcBot) starts sending automated reminders about PRs which were closed without merging.
(but again, perhaps that's something you've already thought of)

**Comment by hedss** [comment]
#6 would not be implemented by VersionBot. There'd be a StatusBot or the like that would get information on all the repos it currently has attached to it and then has a timeout to go and check all **open** PRs (not PRs that have been closed without/with merging).

Again, this comes down to selectiveness about what a ProcBot listens to. There's a registration scheme in the ProcBots that means any derived Bots **only** get what they want, they don't get all events. This is how we can tailor this. Maybe it's worth reading the ProcBot spec and the source code?

**Pull request merged**
