### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by jviotti**
This file makes various compatible editors adhere to the encoding/line
ending/spacing preferences of this project.

Change-Type: patch
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by sqweelygig** [comment]
Can indent size be left unspecified?

**Comment by jviotti** [comment]
Updated to 4! 

> Can indent size be left unspecified?

The whole benefit of `.editorconfig` is to specify these kinds of things, so you don't have to think about them.

**Comment by sqweelygig** [comment]
@jviotti do you in particular want to update and merge this PR, or shall I?  I ask because it's presence is starting to bug me a little.

**Comment by jviotti** [comment]
Done, should be merged automatically as soon as Circle CI finishes.

**Pull request merged**
