### PR TITLE
Docs: Syncbot account (WIP)

### PR DESCRIPTION
**Pull request by imrehg**
Link to where Syncbot is found

### CODE REVIEW

**Comment by imrehg** [comment]
This change is not necessarily to be included here (since it's a public repo), but there should be some docs where to find Syncbot. That's the correct info, right, btw? (when I tried setting things up, it took a while to find).
Or if better, can change this patch to a "How to find Syncbot in your Flowdock setup" instead of the hot linking.

**Comment by hedss** [comment]
@imrehg @sqweelygig @lekkas I'm of the opinion that anything that is general user information for how to use the service should be in `resin-io/process` somewhere (much like how to use VersionBot is in the Commit & PR guide).

**Comment by lekkas** [comment]
agreed @hedss , `resin-io/process` is the place to add internal documentation on how to use syncbot cc @imrehg  @sqweelygig , so this issue should be closed and all relevant documentation transferred there

**Comment by sqweelygig** [comment]
Added this task to the more general https://github.com/resin-io-modules/resin-procbots/issues/115

**Pull request closed without merging**
