### PR TITLE
[Issue #56] Add circle integration

### PR DESCRIPTION
**Pull request by brownjohnf**
Connects to #56

### CODE REVIEW

**Comment by brownjohnf** [comment]
@hedss uh, what happened here? Do you have a rogue bot running as you? It looks like you approved this and then closed it without merging. Was that intentional?

**Comment by hedss** [comment]
@brownjohnf Must have been a rogue click, certainly didn't mean to close it!

**Comment by brownjohnf** [comment]
Am I good to merge, then?

**Comment by hedss** [comment]
Sorry, yes, absolutely, was expecting you to. :)

**Pull request merged**
